# Rename this file to just database.yml, and configure as you need! (localhost)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: user
  password: 'pwd'

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test<%= ENV['TEST_ENV_NUMBER'] %>
